language: node_js
node_js:
- 10.15.3
sudo: require
addons:
  ssh_known_hosts: 134.175.33.133
branches:
  only:
  - production
before_install:
- openssl aes-256-cbc -K $encrypted_12a95cd6f608_key -iv $encrypted_12a95cd6f608_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
script:
- npm install
- npm run dll
- npm run build
after_success:
- rsync -r dist root@134.175.33.133:~/Clash-Royale-PWA --delete
